"""
Generates a simple, clearly-marked "dummy" offer letter PDF for a student
who has been marked as Selected for a drive. Optional feature per the
project spec ("dummy offer letter generator for the company side").
"""
import os
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.pdfgen import canvas


def generate_offer_letter_pdf(*, company_name, student_name, job_title, output_path):
    """Renders a one-page dummy offer letter to `output_path`."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    ink = colors.HexColor("#1B2B4B")
    gold = colors.HexColor("#C08A2E")
    muted = colors.HexColor("#6B7280")

    # Header bar
    c.setFillColor(ink)
    c.rect(0, height - 28 * mm, width, 28 * mm, fill=True, stroke=False)
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(20 * mm, height - 17 * mm, company_name)
    c.setFont("Helvetica", 10)
    c.setFillColor(colors.HexColor("#C7CCDA"))
    c.drawString(20 * mm, height - 23 * mm, "Offer of Employment")

    # Watermark-style "DUMMY / SAMPLE" notice (this is a demo document, not a legal offer)
    c.setFillColor(gold)
    c.setFont("Helvetica-BoldOblique", 9)
    c.drawRightString(width - 20 * mm, height - 17 * mm, "SAMPLE DOCUMENT")
    c.setFillColor(colors.HexColor("#E8CFA0"))
    c.drawRightString(width - 20 * mm, height - 22 * mm, "Generated by Placement Portal")

    y = height - 45 * mm
    c.setFillColor(colors.black)
    c.setFont("Helvetica", 11)

    today_str = datetime.utcnow().strftime("%d %B %Y")
    c.drawString(20 * mm, y, f"Date: {today_str}")
    y -= 12 * mm

    c.drawString(20 * mm, y, f"Dear {student_name},")
    y -= 10 * mm

    body_lines = [
        f"We are pleased to offer you the position of {job_title} at {company_name}, following",
        "your successful participation in our campus placement process. This letter confirms",
        "your selection through the institute's Placement Portal.",
        "",
        "This is a sample/dummy offer letter generated for demonstration purposes as part of",
        "the placement portal's application workflow, and does not constitute a legally binding",
        "employment contract. A formal offer letter with complete terms of employment will",
        "follow through official company channels.",
        "",
        "We look forward to welcoming you to the team.",
    ]
    c.setFont("Helvetica", 10.5)
    for line in body_lines:
        c.drawString(20 * mm, y, line)
        y -= 7 * mm

    y -= 10 * mm
    c.setFont("Helvetica", 10.5)
    c.drawString(20 * mm, y, "Sincerely,")
    y -= 7 * mm
    c.setFont("Helvetica-Bold", 10.5)
    c.drawString(20 * mm, y, f"Human Resources, {company_name}")

    # Footer
    c.setFillColor(muted)
    c.setFont("Helvetica-Oblique", 8)
    c.drawCentredString(
        width / 2, 12 * mm,
        "This document was generated automatically by the Placement Portal Application and is not a legal document."
    )

    c.showPage()
    c.save()
    return output_path
